config/routes.rb
LoginRails::Application.routes.draw do

  scope '(:locale)' do
    resources :forums
    resources :channels
    resources :posts

    get "static/index"
    
    get 'admin' => 'admin#index'
    get 'admin/users'
    get 'admin/forums'

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    get "sessions/create"
    get "sessions/destroy"

    controller :users do
      get 'register' => :new
      get 'profile/:id' => :show, as: :profile
    end
    
    resources :users
    
    root 'static#index'
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base
	belongs_to :forum
	belongs_to :user
	has_many :posts, dependent: :destroy
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: [:show, :edit, :update, :destroy]

  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel.counter += 1
    @channel.save
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # GET /channels/1/edit
  def edit
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(channel_params)
    @channel.counter = 0
    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render action: 'show', status: :created, location: @channel }
      else
        format.html { render action: 'new' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /channels/1
  # PATCH/PUT /channels/1.json
  def update
    respond_to do |format|
      if @channel.update(channel_params)
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_channel
      @channel = Channel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def channel_params
      # params[:channel]
      params.require(:channel).permit(:title, :body, :user_id, :forum_id)
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.slim
= form_for @channel do |f|
  - if @channel.errors.any?
    #error_explanation
      h2 = "#{pluralize(@channel.errors.count, "error")} prohibited this channel from being saved:"
      ul
        - @channel.errors.full_messages.each do |message|
          li = message
  = f.hidden_field :forum_id, value: params[:forum_id]
  = f.hidden_field :user_id, value: session[:user_id]
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body  
  .actions = f.submit 'Save'

app/views/channels/edit.html.slim
h1 Editing channel

== render 'form'

= link_to 'Show', @channel
'|
= link_to 'Back', channels_path

app/views/channels/index.html.slim
h1 Listing channels

table
  tr
    th
    th
    th

  - @channels.each do |channel|
    tr
      td = link_to 'Show', channel
      td = link_to 'Edit', edit_channel_path(channel)
      td = link_to 'Destroy', channel, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Channel', new_channel_path

app/views/channels/new.html.slim
h1 New channel

== render 'form'

= link_to 'Back'

app/views/channels/show.html.slim
br
.row
	.col-md-6
		= link_to 'Back', forum_path(@channel.forum_id), class: 'btn btn-default btn-sm'
		|&nbsp;
		= link_to 'Reply', new_post_path(channel_id: @channel), class: 'btn btn-primary btn-sm'
	.clearfix
hr
.cs-post
	.col-md-3
		h4 = @channel.user.username.capitalize
	.col-md-9
		h4 = @channel.title
		hr
		p = @channel.body
	.clearfix
- @channel.posts.each do |post|
	.cs-post
		.col-md-3
			h4 = post.user.username.capitalize
		.col-md-9
			- unless post.title.empty?
				h4 = post.title
				hr
			p style="padding-top:10px;" = post.body
		.clearfix