config/routes.rb
LoginRails::Application.routes.draw do

  scope '(:locale)' do
    resources :forums
    resources :channels
    resources :posts

    get "static/index"
    
    get 'admin' => 'admin#index'
    get 'admin/users'
    get 'admin/forums'

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    get "sessions/create"
    get "sessions/destroy"

    controller :users do
      get 'register' => :new
      get 'profile/:id' => :show, as: :profile
    end
    
    resources :users
    
    root 'static#index'
  end

end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :channels, dependent: :destroy
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :set_forum, only: [:show, :edit, :update, :destroy]
  before_action 'authorize_admin', except: [:index]
  # GET /forums
  # GET /forums.json
  def index
    @forums = Forum.all
  end

  # GET /forums/1
  # GET /forums/1.json
  def show
  end

  # GET /forums/new
  def new
    @forum = Forum.new
  end

  # GET /forums/1/edit
  def edit
  end

  # POST /forums
  # POST /forums.json
  def create
    @forum = Forum.new(forum_params)

    respond_to do |format|
      if @forum.save
        format.html { redirect_to @forum, notice: 'Forum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @forum }
      else
        format.html { render action: 'new' }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forums/1
  # PATCH/PUT /forums/1.json
  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to @forum, notice: 'Forum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forums/1
  # DELETE /forums/1.json
  def destroy
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to forums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forum
      @forum = Forum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def forum_params
      params.require(:forum).permit(:name, :description)
    end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.slim
= form_for @forum do |f|
  - if @forum.errors.any?
    #error_explanation
      h2 = "#{pluralize(@forum.errors.count, "error")} prohibited this forum from being saved:"
      ul
        - @forum.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit 'Save'

app/views/forums/_list_forums.html.slim
h1 Listing forums

table.table.table-bordered.table-striped.table-condensed
  tr
    th Name
    th Description
    th
    th
    th

  - @forums.each do |forum|
    tr
      td = forum.name
      td = forum.description
      td = link_to 'Show', forum
      td = link_to 'Edit', edit_forum_path(forum)
      td = link_to 'Destroy', forum, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Forum', new_forum_path, class: 'btn btn-default btn-sm'

app/views/forums/edit.html.slim
h1 Editing forum

== render 'form'

= link_to 'Show', @forum
'|
= link_to 'Back', forums_path

app/views/forums/index.html.slim
h1 Listing forums

table
  tr
    th Name
    th Description
    th
    th
    th

  - @forums.each do |forum|
    tr
      td = forum.name
      td = forum.description
      td = link_to 'Show', forum
      td = link_to 'Edit', edit_forum_path(forum)
      td = link_to 'Destroy', forum, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Forum', new_forum_path

app/views/forums/new.html.slim
h1 New forum

== render 'form'

= link_to 'Back', forums_path

app/views/forums/show.html.slim
br
.panel.panel-default
  .panel-heading Forum Detail
  .panel-body
    h4 
      = @forum.name 
      small &nbsp; #{@forum.description}
= link_to "Create Channel", new_channel_path(forum_id: @forum), class: 'btn btn-primary btn-sm'
.clearfix
br
- if @forum.channels.empty?
  .alert.alert-danger.text-center
    = icon('meh-o', '', class: 'fa-5x')
    p Channel not found
- else
  table.table.table-bordered.table-stripped
    tr
      th 
      th Title
      th Author
      th Views
    - @forum.channels.each do |channel|
      tr
        td = icon('archive')
        td = link_to channel.title, channel_path(channel)
        td = icon('user', channel.user.username.capitalize)
        td = icon('eye', channel.counter)