config/routes.rb
LoginRails::Application.routes.draw do

  scope '(:locale)' do
    resources :forums
    resources :channels
    resources :posts

    get "static/index"
    
    get 'admin' => 'admin#index'
    get 'admin/users'
    get 'admin/forums'

    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end

    get "sessions/create"
    get "sessions/destroy"

    controller :users do
      get 'register' => :new
      get 'profile/:id' => :show, as: :profile
    end
    
    resources :users
    
    root 'static#index'
  end

end

app/views/layouts/admin.html.slim
doctype HTML
html
  head
    title Login Rails
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    #side-bar.col-md-2.height-fluid
      .heading
        h3
          strong Control Panel
        h4 style="letter-spacing:-1px;" Hi, #{get_user.capitalize}
      .row
        hr
      .row
        .list-group
          = link_to root_url, class: 'list-group-item bordered' do
            = icon('home', 'Look Website', class: 'fa-lg')
          = link_to admin_forums_path, class: 'list-group-item bordered', remote: true do
            = icon('comments', 'Forums', class: 'fa-lg')
          = link_to login_path, class: 'list-group-item bordered' do
            = icon('rss', 'Threads', class: 'fa-lg')
          = link_to admin_users_path, class: 'list-group-item bordered', remote: true do
            = icon('users', 'Users', class: 'fa-lg')
          = link_to logout_path, method: :delete, class: 'list-group-item bordered' do
            = icon('sign-out', 'Logout', class: 'fa-lg')
    #content.col-md-10
      = yield
    .clearfix

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoginRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.slim
doctype HTML
html
  head
    title Tesseract
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    #fb-root
    javascript:
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s);
        js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=288641757957965";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    nav.navbar.navbar-default role="navigation"
      .container
        .container-fluid
          .navbar-header
            a.navbar-brand href="#{root_url}" Tesseract
          = form_tag root_url, class: 'navbar-form navbar-left locale', method: 'get' do
            = select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()', class: 'form-control input-sm'
            = submit_tag 'submit'
            = javascript_tag "$('.locale input').hide()"
          ul.nav.navbar-nav
            li
              = link_to "Forum", forums_path
          ul.nav.navbar-nav.navbar-right
            - if session[:user_id].nil?
              li
                = link_to t('register'), register_url
              li.active
                = link_to t('.login'), login_url
            - else
              li
                = link_to get_user.capitalize, profile_path(session[:user_id])
              li.active
                = link_to t('.logout'), logout_url, method: :delete
    - if notice
      .container
        .row
          .col-md-12
            .alert.alert-warning = notice
          .clearfix
    - if current_page?(root_url)
      #carousel-home.carousel.slide data-ride="carousel"
        / Wrapper for slides
        .carousel-inner
          .item.active
            img src="assets/0.jpg" alt="slider 1"
          .item
            img src="assets/1.jpg" alt="slider 2"
          .item
            img src="assets/2.jpg" alt="slider 3"
          .item
            img src="assets/3.jpg" alt="slider 4"
          .item
            img src="assets/4.jpg" alt="slider 5"
      javascript:
        $('.carousel').carousel({
          interval: 5000,
          pause: "hover",
            wrap: true
        });
    .container
      = yield